services:
  db:
    image: postgres:15-alpine
    container_name: securevault-db

    environment:
      POSTGRES_USER: securevault
      POSTGRES_PASSWORD: securevault_pass
      POSTGRES_DB: securevault

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: